# Generated by Django 5.2.12 on 2026-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('daily_rate', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
