# Generated by Django 5.2.12 on 2026-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_rolename_alter_employer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='rolename',
        ),
        migrations.AlterField(
            model_name='employer',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
