# Generated by Django 5.2.12 on 2026-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employer_rolename_alter_employer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='rolename',
            field=models.CharField(default='employer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='role',
            field=models.CharField(default='employer', max_length=100),
        ),
    ]
