# Generated by Django 5.2.12 on 2026-03-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_employer_rolename_alter_employer_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='rolename',
            new_name='job_role',
        ),
    ]
