# Generated by Django 5.2.12 on 2026-03-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_rename_rolename_employer_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
