# Generated by Django 5.2.12 on 2026-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_employer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employer_profiles/'),
        ),
    ]
