# Generated by Django 5.2.12 on 2026-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_employer_is_verified_employer_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
