# Generated by Django 5.2.12 on 2026-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_employer_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='delete_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
