# Generated by Django 5.2.12 on 2026-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_employer_delete_message_employer_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
