# Generated by Django 5.2.12 on 2026-04-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_employer_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='temp_password',
        ),
    ]
