# Generated by Django 5.2.12 on 2026-04-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0009_remove_employer_verification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='verification/face/')),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='verification/aadhar/')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='verification/pan/')),
                ('driving_licence_image', models.ImageField(blank=True, null=True, upload_to='verification/licence/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employer_unique_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='employer.employer')),
            ],
        ),
    ]
