# Generated by Django 5.2.12 on 2026-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerverification',
            name='is_alert_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerverification',
            name='is_alert_removed',
            field=models.BooleanField(default=False),
        ),
    ]
