# Generated by Django 5.2.12 on 2026-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_employerverification_is_alert_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
