# Generated by Django 5.2.12 on 2026-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_employerverification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerverification',
            name='is_alert_read',
        ),
        migrations.RemoveField(
            model_name='employerverification',
            name='is_alert_removed',
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
