# Generated by Django 5.2.12 on 2026-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_remove_employerverification_is_alert_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerverification',
            name='aadhar_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='driving_licence_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='face_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='pan_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
