# Generated by Django 5.2.12 on 2026-05-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_remove_employer_temp_password'),
        ('verification', '0005_alter_employerverification_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerverification',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='employer.employer')),
            ],
        ),
    ]
