# Generated by Django 5.2.12 on 2026-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_employerverification_status_employeralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerverification',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='driving_licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification/licence/'),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification/face/'),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification/pan/'),
        ),
    ]
