# Generated by Django 5.2.12 on 2026-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_alter_employerverification_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerverification',
            name='is_alert_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerverification',
            name='is_alert_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmployerAlert',
        ),
    ]
