# Generated by Django 6.0.6 on 2026-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=20)),
                ('recipient_id', models.IntegerField()),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('HIRE_REQUEST', 'Hire Request'), ('HIRE_ACCEPTED', 'Hire Accepted'), ('HIRE_REJECTED', 'Hire Rejected')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
