# Generated by Django 6.0.6 on 2026-06-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_status', models.CharField(choices=[('generated', 'Generated'), ('verified', 'Verified'), ('expired', 'Expired')], default='generated', max_length=20)),
                ('payment_amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='Online', max_length=50)),
                ('hire_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='hire_request.hirerequest')),
            ],
        ),
    ]
