# Generated by Django 6.0.6 on 2026-06-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_request', '0002_jobprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprogress',
            name='customer_review_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobprogress',
            name='customer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobprogress',
            name='employer_review_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobprogress',
            name='employer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
