# Generated by Django 5.2.12 on 2026-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullname',
            new_name='username',
        ),
    ]
