# Generated by Django 5.2.12 on 2026-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_fullname_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
