# Generated by Django 5.2.12 on 2026-03-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
