# Generated by Django 5.2.12 on 2026-04-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_reset', '0002_emailotp_delete_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
