# Generated by Django 6.0.6 on 2026-06-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hire_request', '0003_jobprogress_customer_review_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(max_length=20)),
                ('reviewer_id', models.IntegerField()),
                ('receiver_role', models.CharField(max_length=20)),
                ('receiver_id', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('work_quality', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
                ('professionalism', models.IntegerField(blank=True, null=True)),
                ('behaviour', models.IntegerField(blank=True, null=True)),
                ('payment_experience', models.IntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hire_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hire_request.hirerequest')),
            ],
            options={
                'unique_together': {('hire_request', 'reviewer_role')},
            },
        ),
    ]
